import Head from "next/head";
import Filter from "./components/Filter";
import Search from "./components/SearchBar";
import { FaRegNewspaper } from "react-icons/fa";

export default function Home() {
  return (
    <div className="body">
      <Head>
        <title>Repositorio Uniplac</title>
        <meta name="description" content="Generated by NIU" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#003157] p-2 flex flex-row space-x-4 justify-center rounded-tr-md rounded-tl-md mb-1">
        <h1 className="text-2xl text-white font-sans">Pesquisar:</h1>
        <Search/>
      </div>
      <div className="bg-white rounded-bl-md rounded-br-md shadow-lg p-1">
        <div className="flex flex-col-reverse md:space-x-1 md:flex-row">
          <div className="basis-1/2 rounded-sm shadow-sm bg-gray-100 p-1">
            <h1 className="font-bold font-sans py-1">Últimos Materiais Indexados</h1>
            <hr></hr>
            <div className="border-b-gray-400 border-b hover:underline text-end" id="item 1">
              <span className="bg-blue-200 rounded-md mx-1 px-1 text-sm font-sans">Tag item</span>
              <h2 className="font-sans text-sm flex text-justify text-blue-700 cursor-pointer py-1"><span className="text-lg pr-2 text-black"><FaRegNewspaper /></span>IMPLANTAÇÃO DE UMA COZINHA DE LAMA NA ESCOLA DE EDUCAÇÃO INFANTIL: BRINCANDO COM ELEMENTOS DA NATUREZA</h2>
              <div className="text-sm  my-1 ml-2 flex flex-row">
                <span className="font-sans">indexado em: {'agosto, 18, 2022'}</span>
              </div>
            </div>
          </div>
          <div className="basis-1/2 rounded-sm shadow-sm bg-gray-100 p-1">
            <h1 className="font-bold font-sans py-1">Últimas Dissertações</h1>
            <hr></hr>
          </div>

        </div>
      </div>
    </div>
  );
}

/*
      <Search/>
      <Filter />
                <div className="basis-1/5 rounded-sm shadow-sm">
            <h1 className="font-bold font-sans py-1">Filtro</h1>
            <hr></hr>
            <form>
              <main className="sm:flow-root px-4 py-4 overflow-y-auto font-sans bg-gray-200 text-center md:text-start">
                <div className="-my-8 divide-y divide-gray-100">
                  <div className="py-8">
                    <fieldset>
                      <legend className="text-xl font-medium">Repositório</legend>

                      <ul className="grid grid-cols-1 gap-3 mt-5">
                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200"
                            />
                            <span className="ml-3 font-medium">Periódicos</span>
                          </label>
                        </li>

                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200 "
                            />
                            <span className="ml-3 font-medium">Artigos</span>
                          </label>
                        </li>

                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200"
                            />
                            <span className="ml-3 font-medium">Livros</span>
                          </label>
                        </li>
                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200"
                            />
                            <span className="ml-3 font-medium">TCCS</span>
                          </label>
                        </li>
                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200 "
                            />
                            <span className="ml-3 font-medium">Monografias</span>
                          </label>
                        </li>
                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200"
                            />
                            <span className="ml-3 font-medium">Dissertações</span>
                          </label>
                        </li>
                      </ul>
                    </fieldset>
                  </div>

                  <div className="py-4">
                    <fieldset>
                      <legend className="text-xl font-medium">Filtros</legend>

                      <ul className="grid grid-cols-1 gap-3 mt-5">
                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200"
                            />
                            <span className="ml-3 font-medium">Autor</span>
                          </label>
                        </li>

                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200 "
                            />
                            <span className="ml-3 font-medium">Assunto</span>
                          </label>
                        </li>

                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200"
                            />
                            <span className="ml-3 font-medium">Data</span>
                          </label>
                        </li>
                      </ul>
                    </fieldset>
                  </div>

                  <div className="py-4">
                    <fieldset>
                      <legend className="text-xl font-medium">Tags</legend>

                      <ul className="grid grid-cols-1 gap-3 mt-5">
                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200"
                            />
                            <span className="ml-3 font-medium">Mediciona</span>
                          </label>
                        </li>

                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200 "
                            />
                            <span className="ml-3 font-medium">Psicologia</span>
                          </label>
                        </li>

                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200"
                            />
                            <span className="ml-3 font-medium">Odotologia</span>
                          </label>
                        </li>
                        <li>
                          <label className="flex items-center text-sm">
                            <input
                              type="checkbox"
                              className="w-4 h-4 border border-gray-200"
                            />
                            <span className="ml-3 font-medium">Mestrado</span>
                          </label>
                        </li>

                      </ul>
                    </fieldset>
                  </div>
                </div>
                <div className="pt-10 text-end md:text-center">
                  <button className="text-sm font-medium text-gray-600 underline" type="button">
                    Limpar filtros
                  </button>
                </div>
              </main>
            </form>
          </div>
*/