import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Repositorio Uniplac</title>
        <meta name="description" content="Generated by NIU" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   
    </div>
  );
}
