import Head from "next/head";
import Filter from "./components/Filter";
import Search from "./components/SearchBar";

export default function Home() {
  return (
    <div className="body">
      <Head>
        <title>Repositorio Uniplac</title>
        <meta name="description" content="Generated by NIU" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search/>
      <Filter />
    </div>
  );
}
